//
// SharedCitiesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SharedCitiesAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCities(completion: @escaping ((_ data: [CityGetApiModel]?,_ error: Error?) -> Void)) {
        getCitiesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/cities
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example=[ {
  "TimeZoneId" : "TimeZoneId",
  "Id" : 0,
  "Name" : "Name"
}, {
  "TimeZoneId" : "TimeZoneId",
  "Id" : 0,
  "Name" : "Name"
} ]}]

     - returns: RequestBuilder<[CityGetApiModel]> 
     */
    open class func getCitiesWithRequestBuilder() -> RequestBuilder<[CityGetApiModel]> {
        let path = "/api/shared/cities"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[CityGetApiModel]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCity(id: Int, completion: @escaping ((_ data: CityGetApiModel?,_ error: Error?) -> Void)) {
        getCityWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/cities/{id}
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "TimeZoneId" : "TimeZoneId",
  "Id" : 0,
  "Name" : "Name"
}}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<CityGetApiModel> 
     */
    open class func getCityWithRequestBuilder(id: Int) -> RequestBuilder<CityGetApiModel> {
        var path = "/api/shared/cities/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CityGetApiModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
