//
// SharedCurrenciesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


/*
open class SharedCurrenciesAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCurrencies(completion: @escaping ((_ data: [Currency]?,_ error: Error?) -> Void)) {
        getCurrenciesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/currencies
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example=[ {
  "Id" : 0,
  "Short" : "Short",
  "Name" : "Name"
}, {
  "Id" : 0,
  "Short" : "Short",
  "Name" : "Name"
} ]}]

     - returns: RequestBuilder<[Currency]> 
     */
    open class func getCurrenciesWithRequestBuilder() -> RequestBuilder<[Currency]> {
        let path = "/api/shared/currencies"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Currency]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCurrency(id: Int, completion: @escaping ((_ data: Currency?,_ error: Error?) -> Void)) {
        getCurrencyWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/currencies/{id}
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "Id" : 0,
  "Short" : "Short",
  "Name" : "Name"
}}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<Currency> 
     */
    open class func getCurrencyWithRequestBuilder(id: Int) -> RequestBuilder<Currency> {
        var path = "/api/shared/currencies/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Currency>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}*/
