//
// SharedMeasurementsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SharedMeasurementsAPI {
    /**

     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMeasurement(id: Int, completion: @escaping ((_ data: Measurement?,_ error: Error?) -> Void)) {
        getMeasurementWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/measurements/{id}
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "Id" : 0,
  "FullMeasurement" : "FullMeasurement",
  "ShortMeasurement" : "ShortMeasurement"
}}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<Measurement> 
     */
    open class func getMeasurementWithRequestBuilder(id: Int) -> RequestBuilder<Measurement> {
        var path = "/api/shared/measurements/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Measurement>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMeasurements(completion: @escaping ((_ data: [Measurement]?,_ error: Error?) -> Void)) {
        getMeasurementsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/measurements
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example=[ {
  "Id" : 0,
  "FullMeasurement" : "FullMeasurement",
  "ShortMeasurement" : "ShortMeasurement"
}, {
  "Id" : 0,
  "FullMeasurement" : "FullMeasurement",
  "ShortMeasurement" : "ShortMeasurement"
} ]}]

     - returns: RequestBuilder<[Measurement]> 
     */
    open class func getMeasurementsWithRequestBuilder() -> RequestBuilder<[Measurement]> {
        let path = "/api/shared/measurements"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Measurement]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
