//
// SharedMeasurementUnitsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SharedMeasurementUnitsAPI {
    /**

     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMeasurementUnit(id: Int, completion: @escaping ((_ data: MeasurementUnit?,_ error: Error?) -> Void)) {
        getMeasurementUnitWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/measurementunits/{id}
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "ShortName" : "ShortName",
  "Id" : 7,
  "Name" : "Name"
}}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<MeasurementUnit> 
     */
    open class func getMeasurementUnitWithRequestBuilder(id: Int) -> RequestBuilder<MeasurementUnit> {
        var path = "/api/shared/measurementunits/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MeasurementUnit>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMeasurementUnits(completion: @escaping ((_ data: [MeasurementUnit]?,_ error: Error?) -> Void)) {
        getMeasurementUnitsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/shared/measurementunits
     - OAuth:
       - type: oauth2
       - name: tokenAuth
     - examples: [{contentType=application/json, example=[ {
  "ShortName" : "ShortName",
  "Id" : 7,
  "Name" : "Name"
}, {
  "ShortName" : "ShortName",
  "Id" : 7,
  "Name" : "Name"
} ]}]

     - returns: RequestBuilder<[MeasurementUnit]> 
     */
    open class func getMeasurementUnitsWithRequestBuilder() -> RequestBuilder<[MeasurementUnit]> {
        let path = "/api/shared/measurementunits"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[MeasurementUnit]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
