//
// CommodityCategoryFieldGetApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CommodityCategoryFieldGetApiModel: Codable {

    public var isInherited: Bool?
    public var isPerVariation: Bool?
    public var isDisplayable: Bool?
    public var isSelectable: Bool?
    public var field: CommodityOptionFieldGetApiModel?


    
    public init(isInherited: Bool?, isPerVariation: Bool?, isDisplayable: Bool?, isSelectable: Bool?, field: CommodityOptionFieldGetApiModel?) {
        self.isInherited = isInherited
        self.isPerVariation = isPerVariation
        self.isDisplayable = isDisplayable
        self.isSelectable = isSelectable
        self.field = field
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(isInherited, forKey: "IsInherited")
        try container.encodeIfPresent(isPerVariation, forKey: "IsPerVariation")
        try container.encodeIfPresent(isDisplayable, forKey: "IsDisplayable")
        try container.encodeIfPresent(isSelectable, forKey: "IsSelectable")
        try container.encodeIfPresent(field, forKey: "Field")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        isInherited = try container.decodeIfPresent(Bool.self, forKey: "IsInherited")
        isPerVariation = try container.decodeIfPresent(Bool.self, forKey: "IsPerVariation")
        isDisplayable = try container.decodeIfPresent(Bool.self, forKey: "IsDisplayable")
        isSelectable = try container.decodeIfPresent(Bool.self, forKey: "IsSelectable")
        field = try container.decodeIfPresent(CommodityOptionFieldGetApiModel.self, forKey: "Field")
    }
}

