//
// CurrentUserSupplierAccessApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CurrentUserSupplierAccessApiModel: Codable {

    public var granted: Bool?
    public var suppliers: [CurrentUserSupplierEntityApiModel]?


    
    public init(granted: Bool?, suppliers: [CurrentUserSupplierEntityApiModel]?) {
        self.granted = granted
        self.suppliers = suppliers
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(granted, forKey: "Granted")
        try container.encodeIfPresent(suppliers, forKey: "Suppliers")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        granted = try container.decodeIfPresent(Bool.self, forKey: "Granted")
        suppliers = try container.decodeIfPresent([CurrentUserSupplierEntityApiModel].self, forKey: "Suppliers")
    }
}

