//
// CurrentUserTerminalEntityApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CurrentUserTerminalEntityApiModel: Codable {

    public var id: Int?
    public var vendor: CurrentUserVendorEntityApiModel?
    public var distributionPoint: CurrentUserDistributionPointEntityApiModel?


    
    public init(id: Int?, vendor: CurrentUserVendorEntityApiModel?, distributionPoint: CurrentUserDistributionPointEntityApiModel?) {
        self.id = id
        self.vendor = vendor
        self.distributionPoint = distributionPoint
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(vendor, forKey: "Vendor")
        try container.encodeIfPresent(distributionPoint, forKey: "DistributionPoint")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        vendor = try container.decodeIfPresent(CurrentUserVendorEntityApiModel.self, forKey: "Vendor")
        distributionPoint = try container.decodeIfPresent(CurrentUserDistributionPointEntityApiModel.self, forKey: "DistributionPoint")
    }
}

