//
// CurrentUserApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CurrentUserApiModel: Codable {

    public var userName: String?
    public var access: CurrentUserAccessApiModel?


    
    public init(userName: String?, access: CurrentUserAccessApiModel?) {
        self.userName = userName
        self.access = access
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(userName, forKey: "UserName")
        try container.encodeIfPresent(access, forKey: "Access")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        userName = try container.decodeIfPresent(String.self, forKey: "UserName")
        access = try container.decodeIfPresent(CurrentUserAccessApiModel.self, forKey: "Access")
    }
}

