//
// CurrentUserAdministratorAccessApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CurrentUserAdministratorAccessApiModel: Codable {

    public var granted: Bool?


    
    public init(granted: Bool?) {
        self.granted = granted
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(granted, forKey: "Granted")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        granted = try container.decodeIfPresent(Bool.self, forKey: "Granted")
    }
}

