//
// CurrentUserVendorAccessApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CurrentUserVendorAccessApiModel: Codable {

    public var granted: Bool?
    public var vendors: [CurrentUserVendorEntityApiModel]?


    
    public init(granted: Bool?, vendors: [CurrentUserVendorEntityApiModel]?) {
        self.granted = granted
        self.vendors = vendors
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(granted, forKey: "Granted")
        try container.encodeIfPresent(vendors, forKey: "Vendors")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        granted = try container.decodeIfPresent(Bool.self, forKey: "Granted")
        vendors = try container.decodeIfPresent([CurrentUserVendorEntityApiModel].self, forKey: "Vendors")
    }
}

