//
// CurrentUserTerminalAccessApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CurrentUserTerminalAccessApiModel: Codable {

    public var granted: Bool?
    public var terminals: [CurrentUserTerminalEntityApiModel]?


    
    public init(granted: Bool?, terminals: [CurrentUserTerminalEntityApiModel]?) {
        self.granted = granted
        self.terminals = terminals
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(granted, forKey: "Granted")
        try container.encodeIfPresent(terminals, forKey: "Terminals")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        granted = try container.decodeIfPresent(Bool.self, forKey: "Granted")
        terminals = try container.decodeIfPresent([CurrentUserTerminalEntityApiModel].self, forKey: "Terminals")
    }
}

