//
// DistributionPointSellerStatisticsGetApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DistributionPointSellerStatisticsGetApiModel: Codable {

    public var id: Int?
    public var name: String?
    public var orders: Int?
    public var income: Double?


    
    public init(id: Int?, name: String?, orders: Int?, income: Double?) {
        self.id = id
        self.name = name
        self.orders = orders
        self.income = income
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(name, forKey: "Name")
        try container.encodeIfPresent(orders, forKey: "Orders")
        try container.encodeIfPresent(income, forKey: "Income")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        name = try container.decodeIfPresent(String.self, forKey: "Name")
        orders = try container.decodeIfPresent(Int.self, forKey: "Orders")
        income = try container.decodeIfPresent(Double.self, forKey: "Income")
    }
}

