//
// EtalonVariationPriceApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class EtalonVariationPriceApiModel: Codable {

    public var calculationPrecision: String?
    public var calculationTime: Double?
    public var startingDate: String?
    public var options: [EtalonVariationPriceOptionApiModel]?


    
    public init(calculationPrecision: String?, calculationTime: Double?, startingDate: String?, options: [EtalonVariationPriceOptionApiModel]?) {
        self.calculationPrecision = calculationPrecision
        self.calculationTime = calculationTime
        self.startingDate = startingDate
        self.options = options
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(calculationPrecision, forKey: "CalculationPrecision")
        try container.encodeIfPresent(calculationTime, forKey: "CalculationTime")
        try container.encodeIfPresent(startingDate, forKey: "StartingDate")
        try container.encodeIfPresent(options, forKey: "Options")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        calculationPrecision = try container.decodeIfPresent(String.self, forKey: "CalculationPrecision")
        calculationTime = try container.decodeIfPresent(Double.self, forKey: "CalculationTime")
        startingDate = try container.decodeIfPresent(String.self, forKey: "StartingDate")
        options = try container.decodeIfPresent([EtalonVariationPriceOptionApiModel].self, forKey: "Options")
    }
}

