//
// EtalonVariationPriceOptionLightApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class EtalonVariationPriceOptionLightApiModel: Codable {

    public var hash: String?
    public var customerPrice: Double?
    public var duration: String?


    
    public init(hash: String?, customerPrice: Double?, duration: String?) {
        self.hash = hash
        self.customerPrice = customerPrice
        self.duration = duration
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(hash, forKey: "Hash")
        try container.encodeIfPresent(customerPrice, forKey: "CustomerPrice")
        try container.encodeIfPresent(duration, forKey: "Duration")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        hash = try container.decodeIfPresent(String.self, forKey: "Hash")
        customerPrice = try container.decodeIfPresent(Double.self, forKey: "CustomerPrice")
        duration = try container.decodeIfPresent(String.self, forKey: "Duration")
    }
}

