//
// MeasurementUnit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class MeasurementUnit: Codable {

    public var id: Int?
    public var name: String
    public var shortName: String


    
    public init(id: Int?, name: String, shortName: String) {
        self.id = id
        self.name = name
        self.shortName = shortName
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encode(name, forKey: "Name")
        try container.encode(shortName, forKey: "ShortName")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        name = try container.decode(String.self, forKey: "Name")
        shortName = try container.decode(String.self, forKey: "ShortName")
    }
}

