//
// Measurement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Measurement: Codable {

    public var id: Int?
    public var fullMeasurement: String
    public var shortMeasurement: String


    
    public init(id: Int?, fullMeasurement: String, shortMeasurement: String) {
        self.id = id
        self.fullMeasurement = fullMeasurement
        self.shortMeasurement = shortMeasurement
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encode(fullMeasurement, forKey: "FullMeasurement")
        try container.encode(shortMeasurement, forKey: "ShortMeasurement")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        fullMeasurement = try container.decode(String.self, forKey: "FullMeasurement")
        shortMeasurement = try container.decode(String.self, forKey: "ShortMeasurement")
    }
}

