//
// ResolveQRCodeResponseApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ResolveQRCodeResponseApiModel: Codable {

    public var success: Bool?
    public var etalonId: Int?


    
    public init(success: Bool?, etalonId: Int?) {
        self.success = success
        self.etalonId = etalonId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(success, forKey: "Success")
        try container.encodeIfPresent(etalonId, forKey: "EtalonId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        success = try container.decodeIfPresent(Bool.self, forKey: "Success")
        etalonId = try container.decodeIfPresent(Int.self, forKey: "EtalonId")
    }
}

