//
// ServiceFee.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ServiceFee: Codable {

    public var id: Int?
    public var name: String
    public var percentage: Double?
    public var minimumValue: Double?
    public var maximumValue: Double?


    
    public init(id: Int?, name: String, percentage: Double?, minimumValue: Double?, maximumValue: Double?) {
        self.id = id
        self.name = name
        self.percentage = percentage
        self.minimumValue = minimumValue
        self.maximumValue = maximumValue
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encode(name, forKey: "Name")
        try container.encodeIfPresent(percentage, forKey: "Percentage")
        try container.encodeIfPresent(minimumValue, forKey: "MinimumValue")
        try container.encodeIfPresent(maximumValue, forKey: "MaximumValue")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        name = try container.decode(String.self, forKey: "Name")
        percentage = try container.decodeIfPresent(Double.self, forKey: "Percentage")
        minimumValue = try container.decodeIfPresent(Double.self, forKey: "MinimumValue")
        maximumValue = try container.decodeIfPresent(Double.self, forKey: "MaximumValue")
    }
}

