//
// ShowcaseEtalonGetApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ShowcaseEtalonGetApiModel: Codable {

    public var etalon: EtalonGetApiModel?
    public var qRCodeImageId: UUID?
    public var enabled: Bool?


    
    public init(etalon: EtalonGetApiModel?, qRCodeImageId: UUID?, enabled: Bool?) {
        self.etalon = etalon
        self.qRCodeImageId = qRCodeImageId
        self.enabled = enabled
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(etalon, forKey: "Etalon")
        try container.encodeIfPresent(qRCodeImageId, forKey: "QRCodeImageId")
        try container.encodeIfPresent(enabled, forKey: "Enabled")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        etalon = try container.decodeIfPresent(EtalonGetApiModel.self, forKey: "Etalon")
        qRCodeImageId = try container.decodeIfPresent(UUID.self, forKey: "QRCodeImageId")
        enabled = try container.decodeIfPresent(Bool.self, forKey: "Enabled")
    }
}

