//
// SupplierManualGetApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SupplierManualGetApiModel: Codable {

    public var id: Int?
    public var name: String?
    public var file: UploadedFileGetApiModel?
    public var _default: Bool?


    
    public init(id: Int?, name: String?, file: UploadedFileGetApiModel?, _default: Bool?) {
        self.id = id
        self.name = name
        self.file = file
        self._default = _default
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(name, forKey: "Name")
        try container.encodeIfPresent(file, forKey: "File")
        try container.encodeIfPresent(_default, forKey: "Default")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        name = try container.decodeIfPresent(String.self, forKey: "Name")
        file = try container.decodeIfPresent(UploadedFileGetApiModel.self, forKey: "File")
        _default = try container.decodeIfPresent(Bool.self, forKey: "Default")
    }
}

