//
// UploadImageResolveApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class UploadImageResolveApiModel: Codable {

    public var identifiers: [UUID]?


    
    public init(identifiers: [UUID]?) {
        self.identifiers = identifiers
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(identifiers, forKey: "Identifiers")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        identifiers = try container.decodeIfPresent([UUID].self, forKey: "Identifiers")
    }
}

