//
// UploadedImageVariationGetApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class UploadedImageVariationGetApiModel: Codable {

    public var id: String?
    public var _extension: String?
    public var path: String?


    
    public init(id: String?, _extension: String?, path: String?) {
        self.id = id
        self._extension = _extension
        self.path = path
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(_extension, forKey: "Extension")
        try container.encodeIfPresent(path, forKey: "Path")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(String.self, forKey: "Id")
        _extension = try container.decodeIfPresent(String.self, forKey: "Extension")
        path = try container.decodeIfPresent(String.self, forKey: "Path")
    }
}

