//
// VendorEtalonSetApiGetModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class VendorEtalonSetApiGetModel: Codable {

    public var id: Int?
    public var name: String?
    public var etalons: [Int]?


    
    public init(id: Int?, name: String?, etalons: [Int]?) {
        self.id = id
        self.name = name
        self.etalons = etalons
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(name, forKey: "Name")
        try container.encodeIfPresent(etalons, forKey: "Etalons")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        name = try container.decodeIfPresent(String.self, forKey: "Name")
        etalons = try container.decodeIfPresent([Int].self, forKey: "Etalons")
    }
}

