//
// VendorWithDistributionPointsGetApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class VendorWithDistributionPointsGetApiModel: Codable {

    public var id: Int?
    public var companyName: String?
    public var logoId: UUID?
    public var distributionPoints: [DistributionPointGetApiModel]?


    
    public init(id: Int?, companyName: String?, logoId: UUID?, distributionPoints: [DistributionPointGetApiModel]?) {
        self.id = id
        self.companyName = companyName
        self.logoId = logoId
        self.distributionPoints = distributionPoints
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(companyName, forKey: "CompanyName")
        try container.encodeIfPresent(logoId, forKey: "LogoId")
        try container.encodeIfPresent(distributionPoints, forKey: "DistributionPoints")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        companyName = try container.decodeIfPresent(String.self, forKey: "CompanyName")
        logoId = try container.decodeIfPresent(UUID.self, forKey: "LogoId")
        distributionPoints = try container.decodeIfPresent([DistributionPointGetApiModel].self, forKey: "DistributionPoints")
    }
}

