//
// VendorGetOfferApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class VendorGetOfferApiModel: Codable {

    public var offerText: String?


    
    public init(offerText: String?) {
        self.offerText = offerText
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(offerText, forKey: "OfferText")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        offerText = try container.decodeIfPresent(String.self, forKey: "OfferText")
    }
}

