//
// VendorGetApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class VendorGetApiModel: Codable {

    public var id: Int?
    public var companyName: String?
    public var logoId: UUID?


    
    public init(id: Int?, companyName: String?, logoId: UUID?) {
        self.id = id
        self.companyName = companyName
        self.logoId = logoId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(companyName, forKey: "CompanyName")
        try container.encodeIfPresent(logoId, forKey: "LogoId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        companyName = try container.decodeIfPresent(String.self, forKey: "CompanyName")
        logoId = try container.decodeIfPresent(UUID.self, forKey: "LogoId")
    }
}

